import type { EventPageConfig } from './EventPage'

export const eventConfigs: Record<string, EventPageConfig> = {

  // ── Party Hire ──────────────────────────────────────────────
  'outdoor-games': {
    slug: 'outdoor-games', category: 'Party Hire',
    title: 'Outdoor Games',
    tagline: 'Take the fun outside — high-energy games built for open spaces and big crowds.',
    description: 'Our outdoor game hire brings the energy to any open-air event. From bouncing castles to giant lawn games, we set everything up so you can focus on having a great time. Perfect for garden parties, school fields, community grounds, and outdoor venues of all sizes.',
    heroImage: '/games/Bouncing Castles.png',
    highlights: ['Full delivery & setup included', 'Suitable for all ages', 'Indoor & outdoor options', 'Flexible hire durations'],
    recommendedGameIds: ['bouncing-castles', 'cornhole', 'mini-golf', 'giant-jenga', 'ring-toss', 'trampolines', 'giant-connect-4'],
  },
  'indoor-games': {
    slug: 'indoor-games', category: 'Party Hire',
    title: 'Indoor Games',
    tagline: 'Bring the party inside — games that thrive in any indoor space.',
    description: 'Rain or shine, our indoor game hire keeps the energy going. From retro console stations to classic board games and VR sets, we have everything you need to turn any hall, office, or living room into an unforgettable game zone.',
    heroImage: '/games/Playstation Sets.png',
    highlights: ['Works in any indoor space', 'Retro & modern options', 'All equipment provided', 'Setup & collection included'],
    recommendedGameIds: ['playstation-sets', 'virtual-reality', 'chess-boards', 'ludo-boards', 'carrom-board', 'tic-tac-toe', 'darts-board'],
  },
  'quick-service': {
    slug: 'quick-service', category: 'Party Hire',
    title: 'Quick Service Hire',
    tagline: 'Need it fast? We deliver, set up, and collect — stress-free game hire on your schedule.',
    description: 'Our Quick Service hire is designed for clients who need a seamless, no-fuss experience. Choose your games, tell us your date and location, and we handle everything from delivery to collection. Available for daily and weekend bookings.',
    heroImage: '/games/Giant Jenga.png',
    highlights: ['Same-week bookings available', 'Full setup & teardown', 'Flexible daily & weekend rates', 'Dedicated support team'],
    recommendedGameIds: ['giant-jenga', 'cornhole', 'ring-toss', 'tic-tac-toe', 'ludo-boards'],
  },

  // ── Party Planning ───────────────────────────────────────────
  'theme-concepts': {
    slug: 'theme-concepts', category: 'Party Planning',
    title: 'Theme Concepts',
    tagline: 'From retro African vibes to modern game nights — we design themes that tell a story.',
    description: 'A great theme transforms a party into an experience. Our team works with you to develop a cohesive concept — from colour palettes and game selections to décor ideas and activity flow. Whether you want a full AfroRetro cultural theme or something completely custom, we bring it to life.',
    heroImage: '/games/Omweso.png',
    highlights: ['Custom theme development', 'Game & activity curation', 'Décor recommendations', 'Cultural & modern themes'],
    recommendedGameIds: ['omweso', 'carrom-board', 'ludo-boards', 'chess-boards', 'canvas-painting'],
  },
  'live-hosts': {
    slug: 'live-hosts', category: 'Party Planning',
    title: 'Live Hosts',
    tagline: 'A great host keeps the energy alive — ours are pros at making every guest feel included.',
    description: 'Our live hosts are experienced entertainers who know how to read a crowd, run game tournaments, and keep the energy high from start to finish. Available for kids\' parties, corporate events, and everything in between.',
    heroImage: '/games/Clowns Mascots .png',
    highlights: ['Experienced event hosts', 'Tournament facilitation', 'Crowd engagement', 'Available for all event types'],
    recommendedGameIds: ['giant-jenga', 'giant-connect-4', 'cornhole', 'ring-toss', 'tic-tac-toe'],
  },
  'music-sound': {
    slug: 'music-sound', category: 'Party Planning',
    title: 'Music & Sound Packages',
    tagline: 'The right soundtrack makes every game moment hit harder.',
    description: 'Great events need great sound. We can recommend and coordinate music and sound setups that complement your game experience — from background Afrobeats playlists to full PA systems for larger events. Ask us about our partner sound providers.',
    heroImage: '/games/Virtual Reality set.png',
    highlights: ['Background & live music options', 'PA system coordination', 'Afrobeats & retro playlists', 'Partner sound providers'],
    recommendedGameIds: ['playstation-sets', 'virtual-reality', 'bouncing-castles'],
  },
  'birthday-events': {
    slug: 'birthday-events', category: 'Party Planning — Family Events',
    title: 'Birthday Events',
    tagline: 'Make their birthday the one everyone talks about for years.',
    description: 'Birthdays deserve more than cake and balloons. We bring a full game experience to your celebration — tailored to the age group, theme, and vibe you want. From kids\' bouncy castle parties to adult game nights, we make every birthday unforgettable.',
    heroImage: '/games/Bouncing Castles.png',
    highlights: ['Age-appropriate game selection', 'Custom themes available', 'Kids & adult parties', 'Full setup & host options'],
    recommendedGameIds: ['bouncing-castles', 'face-painting', 'giant-jenga', 'giant-connect-4', 'canvas-painting', 'ring-toss'],
  },
  'community-festivals': {
    slug: 'community-festivals', category: 'Party Planning — Family Events',
    title: 'Community Festivals',
    tagline: 'Bring your community together through play, laughter, and shared moments.',
    description: 'Community festivals are about connection. We provide large-scale game setups that cater to all ages — creating activity zones that keep everyone engaged throughout the day. From trampolines for the kids to chess corners for the elders, we cover it all.',
    heroImage: '/games/Trampolines.png',
    highlights: ['Large-scale event setups', 'Multi-age activity zones', 'Cultural game options', 'Full logistics support'],
    recommendedGameIds: ['trampolines', 'bouncing-castles', 'omweso', 'ludo-boards', 'cornhole', 'face-painting', 'canvas-painting'],
  },
  'seasonal-celebrations': {
    slug: 'seasonal-celebrations', category: 'Party Planning — Family Events',
    title: 'Seasonal Celebrations',
    tagline: 'Every season is a reason to celebrate — we bring the games to match the moment.',
    description: 'Christmas, New Year, Easter, Eid, or any cultural celebration — seasonal events deserve a special touch. We curate game experiences that match the spirit of the occasion, bringing families and communities together in the most joyful way.',
    heroImage: '/games/Giant Connect 4.png',
    highlights: ['Seasonal theme curation', 'Family-friendly setups', 'Cultural celebration options', 'Flexible packages'],
    recommendedGameIds: ['giant-connect-4', 'giant-jenga', 'ludo-boards', 'carrom-board', 'bouncing-castles'],
  },

  // ── School Events ────────────────────────────────────────────
  'sports-day': {
    slug: 'sports-day', category: 'School Events',
    title: 'Sports Day Games',
    tagline: 'Make sports day the highlight of the school year — active, competitive, and full of fun.',
    description: 'Our sports day packages bring structured, competitive fun to school grounds. We provide games that encourage teamwork, physical activity, and healthy competition — all supervised and age-appropriate. Perfect for primary and secondary schools.',
    heroImage: '/games/Cornhole.png',
    highlights: ['Age-appropriate activities', 'Team & individual games', 'Supervised & safe', 'Setup on school grounds'],
    recommendedGameIds: ['cornhole', 'ring-toss', 'giant-jenga', 'trampolines', 'bouncing-castles', 'tic-tac-toe'],
  },
  'house-competitions': {
    slug: 'house-competitions', category: 'School Events',
    title: 'House Competitions',
    tagline: 'Fuel the rivalry — structured game tournaments that bring out school spirit.',
    description: 'House competitions are a brilliant way to build school spirit and friendly rivalry. We set up tournament-style game stations where houses compete head-to-head. Our hosts can facilitate scoring, keep energy high, and ensure fair play throughout.',
    heroImage: '/games/Chess Boards.png',
    highlights: ['Tournament-style formats', 'Score tracking support', 'Host facilitation available', 'Indoor & outdoor options'],
    recommendedGameIds: ['chess-boards', 'giant-connect-4', 'giant-jenga', 'carrom-board', 'darts-board', 'table-tennis'],
  },
  'reward-day': {
    slug: 'reward-day', category: 'School Events',
    title: 'Reward Day Activities',
    tagline: 'Celebrate achievement with a day of pure, well-earned fun.',
    description: 'Reward days are special — students have earned it. We create a relaxed, joyful game experience that lets pupils unwind and celebrate. From face painting to VR sets and bouncy castles, we make reward days truly memorable.',
    heroImage: '/games/Face painting.png',
    highlights: ['Fun & relaxed atmosphere', 'Wide variety of activities', 'All ages welcome', 'Full setup & supervision'],
    recommendedGameIds: ['face-painting', 'bouncing-castles', 'virtual-reality', 'canvas-painting', 'playstation-sets', 'trampolines'],
  },
  'team-challenges': {
    slug: 'team-challenges', category: 'School Events — Educational Play',
    title: 'Team Challenges',
    tagline: 'Build teamwork, communication, and problem-solving through play.',
    description: 'Our team challenge activities are designed to develop key skills while keeping students fully engaged. Games are structured to encourage collaboration, strategic thinking, and communication — making learning feel like play.',
    heroImage: '/games/Giant Jenga.png',
    highlights: ['Teamwork-focused activities', 'Strategic game selection', 'Curriculum-aligned options', 'All year groups'],
    recommendedGameIds: ['giant-jenga', 'giant-connect-4', 'chess-boards', 'carrom-board', 'ludo-boards'],
  },
  'stem-booths': {
    slug: 'stem-booths', category: 'School Events — Educational Play',
    title: 'STEM Game Booths',
    tagline: 'Where science, strategy, and play collide — STEM learning through games.',
    description: 'Our STEM game booths use strategic and logic-based games to reinforce STEM concepts in a fun, hands-on way. Chess, Omweso, and other strategy games develop mathematical thinking and problem-solving skills that complement classroom learning.',
    heroImage: '/games/Omweso.png',
    highlights: ['Logic & strategy games', 'Curriculum-linked activities', 'Hands-on learning', 'Primary & secondary levels'],
    recommendedGameIds: ['chess-boards', 'omweso', 'carrom-board', 'giant-connect-4', 'tic-tac-toe'],
  },
  'retro-games-school': {
    slug: 'retro-games-school', category: 'School Events — Educational Play',
    title: 'Interactive Retro Games',
    tagline: 'Introduce students to the games that shaped generations — culturally rich and endlessly fun.',
    description: 'Our interactive retro game sessions introduce students to traditional African and classic games that carry cultural significance. These sessions spark curiosity, cultural appreciation, and healthy competition — all while having a brilliant time.',
    heroImage: '/games/Ludo Boards.png',
    highlights: ['Cultural education through play', 'Traditional African games', 'Interactive & engaging', 'All school levels'],
    recommendedGameIds: ['omweso', 'ludo-boards', 'carrom-board', 'chess-boards'],
  },

  // ── Private Events ───────────────────────────────────────────
  'birthdays-private': {
    slug: 'birthdays-private', category: 'Private Events',
    title: 'Private Birthday Parties',
    tagline: 'Your birthday, your rules — we bring the games, you bring the people.',
    description: 'Private birthday parties deserve a personal touch. We work with you to select games that match your guest list, age range, and vibe — then handle all the setup so you can enjoy every moment. From intimate gatherings to big celebrations, we\'ve got you covered.',
    heroImage: '/games/Giant Connect 4.png',
    highlights: ['Personalised game selection', 'Intimate & large setups', 'Full delivery & collection', 'Host options available'],
    recommendedGameIds: ['giant-connect-4', 'giant-jenga', 'cornhole', 'ring-toss', 'canvas-painting', 'face-painting'],
  },
  'garden-gatherings': {
    slug: 'garden-gatherings', category: 'Private Events',
    title: 'Garden Gatherings',
    tagline: 'Sunshine, good company, and great games — the perfect garden day.',
    description: 'Garden gatherings are all about relaxed fun in a beautiful setting. Our outdoor game hire is perfect for garden parties — we set up games that encourage mingling, laughter, and friendly competition without disrupting the natural flow of your event.',
    heroImage: '/games/Mini Golf Sets.png',
    highlights: ['Outdoor-optimised setups', 'Lawn-friendly equipment', 'Easy setup on grass', 'All ages welcome'],
    recommendedGameIds: ['mini-golf', 'cornhole', 'giant-jenga', 'ring-toss', 'bouncing-castles', 'tic-tac-toe'],
  },
  'milestone-events': {
    slug: 'milestone-events', category: 'Private Events',
    title: 'Milestone Events',
    tagline: 'Graduations, anniversaries, retirements — celebrate the big moments in style.',
    description: 'Milestone events mark the chapters of life worth celebrating. We create sophisticated yet fun game experiences that match the significance of the occasion — bringing guests together through shared play and memorable moments.',
    heroImage: '/games/Chess Boards.png',
    highlights: ['Elegant & fun setups', 'Suitable for all ages', 'Custom game curation', 'Premium presentation'],
    recommendedGameIds: ['chess-boards', 'giant-jenga', 'carrom-board', 'omweso', 'mini-golf', 'virtual-reality'],
  },
  'game-lounge': {
    slug: 'game-lounge', category: 'Private Events — Premium Hire',
    title: 'Game Lounge Setup',
    tagline: 'Transform any space into a premium game lounge your guests won\'t want to leave.',
    description: 'Our game lounge setups create a dedicated entertainment zone within your event space. We arrange multiple game stations in a cohesive, visually appealing layout — giving guests a destination to return to throughout the evening.',
    heroImage: '/games/Playstation Sets.png',
    highlights: ['Multi-station layouts', 'Premium presentation', 'Retro & modern mix', 'Full setup & styling'],
    recommendedGameIds: ['playstation-sets', 'virtual-reality', 'darts-board', 'table-tennis', 'chess-boards', 'carrom-board'],
  },
  'interactive-photo': {
    slug: 'interactive-photo', category: 'Private Events — Premium Hire',
    title: 'Interactive Photo Corners',
    tagline: 'Create moments worth photographing — game-themed photo experiences your guests will love.',
    description: 'Our interactive photo corners combine game setups with photo-worthy moments. Guests play, laugh, and capture memories — creating organic, authentic content that lives on long after the event ends.',
    heroImage: '/games/Clowns Mascots .png',
    highlights: ['Photo-ready game setups', 'Themed props & backdrops', 'Social media friendly', 'Memorable guest experience'],
    recommendedGameIds: ['clowns-mascots', 'face-painting', 'giant-jenga', 'giant-connect-4', 'canvas-painting'],
  },

  // ── Corporate Events ─────────────────────────────────────────
  'office-olympics': {
    slug: 'office-olympics', category: 'Corporate Events — Team Building',
    title: 'Office Olympics',
    tagline: 'Bring out the competitive spirit — a full Olympic-style game day for your team.',
    description: 'Office Olympics is our most popular corporate team-building format. Teams compete across multiple game stations in a structured tournament — building camaraderie, healthy competition, and team spirit in a way that no boardroom exercise can match.',
    heroImage: '/games/Table Tennis.png',
    highlights: ['Tournament-style format', 'Multiple game stations', 'Score tracking & prizes', 'Host facilitation included'],
    recommendedGameIds: ['table-tennis', 'darts-board', 'giant-jenga', 'cornhole', 'giant-connect-4', 'ring-toss'],
  },
  'retro-tournament': {
    slug: 'retro-tournament', category: 'Corporate Events — Team Building',
    title: 'Retro Tournament Nights',
    tagline: 'An evening of retro games, friendly rivalry, and team bonding done right.',
    description: 'Retro Tournament Nights are perfect for after-work team events. We set up a range of classic and retro games in a tournament format — creating an evening of laughter, competition, and genuine connection between colleagues.',
    heroImage: '/games/Carrom Board.png',
    highlights: ['Evening event format', 'Retro game selection', 'Tournament brackets', 'Host & MC available'],
    recommendedGameIds: ['carrom-board', 'chess-boards', 'ludo-boards', 'omweso', 'darts-board', 'playstation-sets'],
  },
  'problem-solving': {
    slug: 'problem-solving', category: 'Corporate Events — Team Building',
    title: 'Problem-Solving Challenges',
    tagline: 'Games that make your team think, collaborate, and win together.',
    description: 'Our problem-solving challenge sessions use strategic games to develop critical thinking, communication, and collaborative decision-making. Ideal for leadership development days, new team integration, and corporate training events.',
    heroImage: '/games/Chess Boards.png',
    highlights: ['Strategy-focused games', 'Leadership development', 'Team integration activities', 'Facilitated debrief available'],
    recommendedGameIds: ['chess-boards', 'giant-connect-4', 'omweso', 'carrom-board', 'giant-jenga'],
  },
  'popup-game-zones': {
    slug: 'popup-game-zones', category: 'Corporate Events — Brand Activations',
    title: 'Pop-Up Game Zones',
    tagline: 'Stop people in their tracks — a branded game zone that creates real engagement.',
    description: 'Pop-up game zones are a powerful brand activation tool. We create eye-catching, interactive game setups at exhibitions, malls, and public spaces that draw crowds, create dwell time, and generate genuine brand engagement.',
    heroImage: '/games/Virtual Reality set.png',
    highlights: ['High foot-traffic setups', 'Brand integration options', 'Crowd-drawing games', 'Flexible locations'],
    recommendedGameIds: ['virtual-reality', 'giant-jenga', 'giant-connect-4', 'bouncing-castles', 'face-painting'],
  },
  'exhibition-attractions': {
    slug: 'exhibition-attractions', category: 'Corporate Events — Brand Activations',
    title: 'Exhibition Attractions',
    tagline: 'Make your exhibition stand the one everyone remembers.',
    description: 'At exhibitions and trade shows, standing out is everything. Our game setups transform your stand into an attraction — drawing visitors in, keeping them engaged, and creating memorable brand interactions that go beyond brochures and banners.',
    heroImage: '/games/Giant Connect 4.png',
    highlights: ['Exhibition-ready setups', 'Compact & large formats', 'Brand-aligned game selection', 'Professional presentation'],
    recommendedGameIds: ['giant-connect-4', 'virtual-reality', 'darts-board', 'ring-toss', 'tic-tac-toe'],
  },
  'family-day': {
    slug: 'family-day', category: 'Corporate Events — Brand Activations',
    title: 'Family Day Entertainment',
    tagline: 'Reward your team and their families with a day of pure, inclusive fun.',
    description: 'Corporate family days are about showing appreciation — to your team and the people who support them. We create multi-age game zones that cater to toddlers, teens, and adults alike, ensuring every family member has an amazing time.',
    heroImage: '/games/Bouncing Castles.png',
    highlights: ['All-age activity zones', 'Kids & adult games', 'Safe & supervised', 'Full event logistics'],
    recommendedGameIds: ['bouncing-castles', 'trampolines', 'face-painting', 'canvas-painting', 'giant-jenga', 'cornhole', 'ludo-boards'],
  },
}
